# Generated by Django 5.0 on 2024-01-18 07:59

import ckeditor.fields
import django.db.models.deletion
import django_resized.forms
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300, verbose_name='Category Name')),
                ('short_description', models.TextField(max_length=1000, verbose_name='Short description')),
                ('image', models.ImageField(upload_to='static/images/')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('user_name', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=130)),
                ('city', models.CharField(max_length=130)),
                ('state', models.CharField(blank=True, max_length=130, null=True)),
                ('address1', models.TextField(max_length=1000)),
                ('address2', models.CharField(max_length=1000)),
                ('postal_code', models.CharField(max_length=130)),
                ('phone_number', models.CharField(max_length=130)),
                ('amount_discounted', models.CharField(max_length=50)),
                ('total_amount', models.CharField(max_length=50)),
                ('shipping_fee', models.CharField(max_length=50)),
                ('total_tax', models.CharField(max_length=50)),
                ('payment_status', models.CharField(choices=[('PENDING', 'PENDING'), ('PAID', 'PAID')], default='PAID', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('DELIVERED', 'delivered')], default='PENDING', max_length=50)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type_name', models.CharField(max_length=200, verbose_name='product type name')),
            ],
            options={
                'verbose_name': 'Product Type',
                'verbose_name_plural': 'Product Types',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('session_key', models.CharField(max_length=40)),
                ('item_name', models.CharField(max_length=300)),
                ('item_category', models.CharField(max_length=300)),
                ('item_product_type', models.CharField(max_length=300)),
                ('item_sku', models.CharField(max_length=200)),
                ('item_image_link', models.CharField(max_length=300)),
                ('item_description', models.CharField(max_length=300)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('variant', models.CharField(blank=True, max_length=50, null=True)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Cart Item',
                'verbose_name_plural': 'Customer Cart Items',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_upload_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('item_name', models.CharField(max_length=300, verbose_name='item name')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('description', ckeditor.fields.RichTextField()),
                ('item_specification', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('sold_out', models.BooleanField(default=False, editable=False, null=True)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sku', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('main_image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[190, 200], upload_to='static/images')),
                ('video', models.FileField(blank=True, null=True, upload_to='static/videos/')),
                ('attribute_list_name', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.category')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.producttype')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/images/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.item')),
            ],
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.item')),
            ],
        ),
        migrations.CreateModel(
            name='MyOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('category_name', models.CharField(max_length=200)),
                ('item_sku', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_orders', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.order')),
            ],
            options={
                'verbose_name': 'My Order',
                'verbose_name_plural': 'My Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('variant', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('item_quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='ecommerce.order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('review_star', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('review_comment', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
