# Generated by Django 5.0 on 2024-01-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_alter_order_address2'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('video', models.FileField(blank=True, null=True, upload_to='static/videos')),
            ],
        ),
    ]
