# Generated by Django 5.0 on 2024-01-30 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0012_item_height_item_length_item_weight_item_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
