# Generated by Django 5.0 on 2024-01-31 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0024_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
