# Generated by Django 5.0 on 2024-02-01 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0026_alter_cart_user_userdetails_delete_useraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_tax',
        ),
    ]
