# Generated by Django 5.0 on 2024-02-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_remove_order_total_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
