# Generated by Django 5.0 on 2024-02-09 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_alter_frontmedia_image_alter_frontmedia_video_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontMedia',
        ),
    ]
