# Generated by Django 5.0 on 2024-02-09 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'image'), ('video', 'video')], max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/frontEnd')),
                ('video', models.FileField(blank=True, null=True, upload_to='static/videos/frontEnd')),
            ],
        ),
        migrations.CreateModel(
            name='TopSliderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
