# Generated by Django 5.0 on 2024-02-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_image', models.ImageField(blank=True, null=True, upload_to='static/images/partner_images')),
                ('partner_designation', models.CharField(max_length=300)),
                ('partner_name', models.CharField(max_length=300)),
            ],
        ),
    ]
