# Generated by Django 4.2 on 2024-02-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_app_manager', '0003_bestsellingproducts_ourmakingvideos_watsapp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watsapp',
            old_name='number',
            new_name='call_text',
        ),
        migrations.AddField(
            model_name='watsapp',
            name='cart_text',
            field=models.CharField(default='asdasd', max_length=50),
            preserve_default=False,
        ),
    ]
