# Generated by Django 4.2 on 2024-02-27 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front_app_manager', '0004_rename_number_watsapp_call_text_watsapp_cart_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ourmakingvideos',
            options={'verbose_name': 'Our Making Videos', 'verbose_name_plural': 'Our Making Videos'},
        ),
    ]
